### PR TITLE
change instance of `fictional` to `fictitious`

### PR DESCRIPTION
**Pull request by ryanpitts**

### CODE REVIEW

**Comment by katydecorah** [comment]
:pray:  :alien: @ryanpitts thank you!

**Comment by ryanpitts** [comment]
my pleasure, and love the map! I always like looking through the data behind projects like this. Not sure why that one caught my eye, other than Jose Chung being one of the greatest episodes :)

I'm curious how you decided lat/lon for fictitious locations. The one nearest where I live is in "Colson, Washington," which isn't a real place -- so how did you decide to place it north of Spokane? Read the blog post but maybe I missed the explanation there.

**Comment by katydecorah** [comment]
@ryanpitts honestly I randomly selected a place (within its state) for the fictional cities and towns - happy to accept PRs for coordinates that prove to be more accurate :stuck_out_tongue:

**Comment by ryanpitts** [comment]
Yeah, not sure I've got a better idea. I guess I could go back and watch "Roland" again and look for visual cues :)

**Pull request merged**
